version: '3.7'
services:
  promtail:
    image: grafana/promtail:master
    ports:
      - "9080:9080"
    volumes:
      - ./server/logs:/logs/server
      - ./misc/promtail/config.yaml:/config/config.yaml
    command: -config.file=/config/config.yaml

  loki:
    image: grafana/loki:master
    volumes:
      - loki_data:/data/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:master
    volumes:
      - grafana_data:/var/lib/grafana
      - ./misc/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"

volumes:
  grafana_data: {}
  loki_data: {}

