server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      __path__: /logs/server/*log.json
      app: server
  pipeline_stages:
    - json: 
        expressions:
          level: "level"
          logger_name: "logger_name"
          thread_name: "thread_name"
    - timestamp:
        source: "@timestamp"
        format: RFC3339Nano
    - labels:
        level:
        logger_name:
        thread_name:

