# config file version
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: "http://prometheus:9090"
    isDefault: true
    access: proxy

  - name: ElasticSearch
    type: elasticsearch
    url: "http://elasticsearch:9200"
    database: "alarmcontrol-logs-*"
    access: proxy
    jsonData:
      esVersion: 70
      logLevelField: ""
      logMessageField: ""
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"


